### ISSUE TITLE
Re-structure Program Directory

### ISSUE THREAD

**Issue by asarephilip** [Greenstand/domain-migration-scripts#10]
It is difficult to build a docker image for this program when we don't have a consistent program directory structure.
Created this [PR](https://github.com/Greenstand/domain-migration-scripts/pull/9) to demonstrate this.  

**Previous Project Directory Structure**
/root_directory
  &ensp;/database
   &ensp;&ensp; knex.js
  &ensp;tree_migration_milestone1.js
  &ensp;package.json
  &ensp;README.md
  &ensp;LICENCE
  &ensp;.gitignore

**Current Project Structure**
/root_directory
  &ensp;/database
    &ensp;ensp;knex.js
  &ensp;/migrateLegacyDataBetweenEnv
    &ensp;&ensp;migration_file_1.js
    &ensp;ensp;migration_file_2.js
     &ensp;&ensp; ...
     &ensp;&ensp;migration_file_n.js
  &ensp;/v1Tov2Migrations
    &ensp;&ensp;/helper
      &ensp;&ensp;&ensp;&ensp;helper_file_1.js
      &ensp;&ensp;&ensp;&ensp;helper_file_2.js
      &ensp;&ensp;&ensp;&ensp;...
      &ensp;&ensp;&ensp;&ensp;helper_file_n.js    
    &ensp;&ensp;migration_file_1.js
    &ensp;&ensp;migration_file_2.js
    &ensp;&ensp;...
    &ensp;&ensp;migration_file_n.js
  &ensp;package.json
  &ensp;README.md
  &ensp;LICENCE
  &ensp;.gitignore

When building a docker image, one would have to specify the files to be copied to build the image. When our project files structure is likely to change over every PR we would have 2 options:
1. Update our Dockerfile every time a program file/directory is added or deleted and the directory structure changes (this will waste our productive time). 
2. Copy every file within the program root directory into the docker image (including files not needed)

**Recommended Program Directory Structure**
/root_directory
  &ensp;/app
    &ensp;&ensp;/src
      &ensp;&ensp;&ensp;# All program directories and program files fall within this directory

When we use this directory structure, all program files will be within the /src directory.
In this case, we only need to copy the /src directory to build the docker image so we would not need to update our Dockerfile on each update. 
Besides, this is a standard directory structure for Node projects.

**Comment by dadiorchen** [comment]
@asarephilip but in this example: https://github.com/Greenstand/treetracker-reporting/blob/main/Dockerfile the source file is also scattered in the root folder, but we are able to build the image and run the node app from the root?

**Comment by asarephilip** [comment]
@dadiorchen 
That is right, this means we will have to copy all the files in the root directory including the files which are not needed. 

If you look at [line 7](https://github.com/Greenstand/treetracker-reporting/blob/main/Dockerfile#L7), we are copying all the files that are in the root folder including the `README file`, `LICENSE`, `.gitignore`, `CONTRIBUTING.md` etc. We don't need this in order to build the docker image. This is the problem I am trying to prevent even though it is not significant at the moment.

We can go ahead with this as the program is very small at this stage.

But let's say the program grows bigger and we decide to use TDD where we would have a lot of test files.
We will be copying all these test unnecessary files.

**Comment by dadiorchen** [comment]
Good observation, but there are some conflict in this stage, we are scattered the code to different branch/repo/folks, so can we postpone this for a while, and after merged all these thing together, then I think it's good to go this direction, so can we make the docker works first then back to this?

**Comment by asarephilip** [comment]
Sure, we can do this.
